[package]
name = "pollnet"
version = "0.5.1"
authors = ["probable-basilisk <basilisk@mtknn.com>"]
edition = "2018"

[dependencies]
tokio-tungstenite = {version = "*", features = ["tls"]}
tungstenite = {version = "*", features = ["tls"]}
futures = "*"
url = "*"
futures-util = "*"
hyper = {version = "*", features = ["server"]}
hyper-staticfile = "*"
http = "*"
nanoid = "*"
reqwest = "*"
log = "*"
env_logger = "*"

[dependencies.tokio]
version = "*"
features = ["sync", "macros", "net"]

[lib]
name = "pollnet"
crate-type = ["cdylib"]
