[package]
name = "pollnet"
version = "0.4.0"
authors = ["probable-basilisk <basilisk@mtknn.com>"]
edition = "2018"

[dependencies]
tokio-tungstenite = {version = "*", features = ["tls"]}
tungstenite = {version = "*", features = ["tls"]}
futures = "*"
url = "*"
futures-util = "*"
hyper = "0.13.6"
hyper-staticfile = "0.5.3"
http = "0.2"
nanoid = "0.3.0"
reqwest = "0.10"

[dependencies.tokio]
version = "*"
features = ["sync", "macros"]

[lib]
name = "pollnet"
crate-type = ["cdylib"]