# Builds and (in the future tests) pull requests
name: Pull Request

on:
  pull_request:
    branches:
      - master
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Cancel existing executions when new commits are pushed onto the branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      # Just directly invoke cargo
      - name: Cargo Build
        run: cargo build --release
        
      - name: Cargo Build (Windows 32 bit)
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --target=i686-pc-windows-msvc --release
