# Builds and releases binaries
name: Release Binaries

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          
      # Just directly invoke cargo
      - name: Cargo Build
        run: cargo build --release
        
      - name: Cargo Build (Windows 32 bit)
        if: matrix.os == 'windows-latest'
        run: |
          rustup target add i686-pc-windows-msvc
          cargo build --target=i686-pc-windows-msvc --release

      - name: Zip (linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir lib
          cp target/release/libpollnet.so lib/
          zip -r "pollnet_${{ matrix.os }}.zip" lib bindings LICENSE README.md
          
      - name: Zip (windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir lib
          mkdir lib32
          cp target/release/pollnet.dll lib/
          cp target/release/pollnet.dll.lib lib/
          cp target/i686-pc-windows-msvc/release/pollnet.dll lib32/
          cp target/i686-pc-windows-msvc/release/pollnet.dll.lib lib32/
          7z a "pollnet_${{ matrix.os }}.zip" lib lib32 bindings LICENSE README.md
          
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: pollnet_${{ matrix.os }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
